package com.sourkanji.sourkanjibackend.model;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import com.sun.istack.NotNull;

@Entity
@Table(name = "deck")
public abstract class Deck {

		private String deckName;
		private List<Card> cardList;
		private Time learnFrequency;
		private Time reviewFrequency;
		private int dailyCardsReviewLimit;
		private Time Time;
		
		public Deck(String deckName) {
			this.deckName = deckName;
			this.cardList = new ArrayList<>();
		}

		public String getDeckName() {
			return deckName;
		}
		public void setDeckName(String deckName) {
			this.deckName = deckName;
		}
		public List<Card> getCardList() {
			return cardList;
		}
		public void setCardList(List<Card> cardList) {
			this.cardList = cardList;
		}
		public Time getLearnFrequency() {
			return learnFrequency;
		}
		public void setLearnFrequency(Time learnFrequency) {
			this.learnFrequency = learnFrequency;
		}
		public Time getReviewFrequency() {
			return reviewFrequency;
		}
		public void setReviewFrequency(Time reviewFrequency) {
			this.reviewFrequency = reviewFrequency;
		}
		public int getDailyCardsReviewLimit() {
			return dailyCardsReviewLimit;
		}
		public void setDailyCardsReviewLimit(int dailyCardsReviewLimit) {
			this.dailyCardsReviewLimit = dailyCardsReviewLimit;
		}

		//loren: Used for debug? auto generated by IDE?
		@Override
		public String toString() {
			return "Deck [deckName=" + deckName + ", cardList=" + cardList + ", learnFrequency=" + learnFrequency
					+ ", reviewFrequency=" + reviewFrequency + ", Time=" + Time + ", getDeckName()=" + getDeckName()
					+ ", getCardList()=" + getCardList() + ", getLearnFrequency()=" + getLearnFrequency()
					+ ", getReviewFrequency()=" + getReviewFrequency() + "getClass()="
					+ getClass() + ", hashCode()=" + hashCode() + ", toString()=" + super.toString() + "]";
		}
	
}

		


	
