package com.sourkanji.sourkanjibackend.model;

import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "deck")
public class Deck {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idDeck;
	
	@Column
	private String deckName;

	@OneToMany(mappedBy = "deck")
	private List<Card> cardList;

	@Column
	private Time learnFrequency;

	@Column
	private Time reviewFrequency;

	@Column
	private int dailyCardsReviewLimit;

	@Column
	private Time Time;

	public Deck(String deckName) {
		this.deckName = deckName;
		this.cardList = new ArrayList<>();
	}

	public String getDeckName() {
		return deckName;
	}

	public void setDeckName(String deckName) {
		this.deckName = deckName;
	}

	public List<Card> getCardList() {
		return cardList;
	}

	public void setCardList(List<Card> cardList) {
		this.cardList = cardList;
	}

	public Time getLearnFrequency() {
		return learnFrequency;
	}

	public void setLearnFrequency(Time learnFrequency) {
		this.learnFrequency = learnFrequency;
	}

	public Time getReviewFrequency() {
		return reviewFrequency;
	}

	public void setReviewFrequency(Time reviewFrequency) {
		this.reviewFrequency = reviewFrequency;
	}

	public int getDailyCardsReviewLimit() {
		return dailyCardsReviewLimit;
	}

	public void setDailyCardsReviewLimit(int dailyCardsReviewLimit) {
		this.dailyCardsReviewLimit = dailyCardsReviewLimit;
	}

	// loren: Used for debug? auto generated by IDE?
	@Override
	public String toString() {
		return "Deck [deckName=" + deckName + ", cardList=" + cardList + ", learnFrequency=" + learnFrequency
				+ ", reviewFrequency=" + reviewFrequency + ", Time=" + Time + ", getDeckName()=" + getDeckName()
				+ ", getCardList()=" + getCardList() + ", getLearnFrequency()=" + getLearnFrequency()
				+ ", getReviewFrequency()=" + getReviewFrequency() + "getClass()="
				+ getClass() + ", hashCode()=" + hashCode() + ", toString()=" + super.toString() + "]";
	}

}
